server {
    listen 80;

    # Konfigurasikan domain
    server_name tugas.uniba-bpn.ac.id;

    root /usr/share/nginx/html;

    # Lokasi untuk file statis React
    location / {
        try_files $uri $uri/ /index.html;  # Pastikan menghandle trailing slash
    }

    # Reverse proxy untuk API
    location /api/ {
        proxy_pass https://backend-course-production-fbd5.up.railway.app/;  # Pastikan backend dapat diakses
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Pengaturan untuk ukuran header dan buffer
    client_max_body_size 10M;
}
